---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@d5d2f8c1bb57169f1ee0617356957de707411e76
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  build-macos:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@d5d2f8c1bb57169f1ee0617356957de707411e76
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
